&id001
name: 브이브이알
keywords:
- VVR .
representative: YoungHoon Mok
members:
  알체라:
    name: 알체라
    keywords:
    - ALCHERA
    representative: 강민수
  포니이엔티:
    name: 포니이엔티
    keywords:
    - 포니이엔티
    representative: 강민호
  한국능률협회:
    name: 한국능률협회
    keywords:
    - KMA
    representative: 강석
  에스와이코마드:
    name: 에스와이코마드
    keywords:
    - 에스와이코마드
    representative: 강선영
  대교:
    name: 대교
    keywords:
    - 대교
    representative: 강순천
  시니스트:
    name: 시니스트
    keywords:
    - 시니스트
    representative: 강신래
  믹스콘엔터테인먼트:
    name: 믹스콘엔터테인먼트
    keywords:
    - MIXCON ENTERTAINMENT
    representative: 강영수
  에쓰핀테크놀로지:
    name: 에쓰핀테크놀로지
    keywords:
    - 에쓰핀테크놀로지
    representative: 강지원
  비브스튜디오스:
    name: 비브스튜디오스
    keywords:
    - VIVE STUDIOS
    representative: 고광민
  하남디지털캠프:
    name: 하남디지털캠프
    keywords:
    - 하남디지털캠프
    representative: 고명
  콘크리에이트:
    name: 콘크리에이트
    keywords:
    - concreate
    representative: 고명미
  위치스:
    name: 위치스
    keywords:
    - 위치스
    representative: 고미아
  케타버스:
    name: 케타버스
    keywords:
    - 케타버스
    representative: 고욱
  비햅틱스:
    name: 비햅틱스
    keywords:
    - 비햅틱스
    representative: 곽기욱
  유니브이알:
    name: 유니브이알
    keywords:
    - 유니브이알
    representative: 곽태진
  포스트미디어:
    name: 포스트미디어
    keywords:
    - 포스트미디어
    representative: 국현규
  앰버린:
    name: 앰버린
    keywords:
    - AMBERIN
    representative: 권기석
  젠스템:
    name: 젠스템
    keywords:
    - ZENSTEM
    representative: 권순재
  LG유플러스:
    name: LG유플러스
    keywords:
    - LG 유플러스
    - LG유플러스
    representative: 권순홍
  헉미디어:
    name: 헉미디어
    keywords:
    - 헉미디어
    representative: 권오철
  아테크넷:
    name: 아테크넷
    keywords:
    - 아테크넷
    representative: 권정열
  스튜디오메타케이:
    name: 스튜디오메타케이
    keywords:
    - 스튜디오메타케이
    representative: 김광집
  서강대학교:
    name: 서강대학교
    keywords:
    - 서강대학교
    representative: 김군주
  레디메이드:
    name: 레디메이드
    keywords:
    - READY MADE
    representative: 김기홍
  미래시티 글로벌:
    name: 미래시티 글로벌
    keywords:
    - 미래시티 글로벌
    representative: 김동우
  AIX랩:
    name: AIX랩
    keywords:
    - AIXLAB
    representative: 김민균
  이노 법률사무소:
    name: 이노 법률사무소
    keywords:
    - 이노 법률사무소
    representative: 김민기
  트러스테이:
    name: 트러스테이
    keywords:
    - 트러스테이
    representative: 김백선
  하나금융TI:
    name: 하나금융TI
    keywords:
    - 하나금융TI
    representative: 김병근
  로코:
    name: 로코
    keywords:
    - LOCO
    representative: 김수련
  메타키움:
    name: 메타키움
    keywords:
    - 메타키움
    representative: 김영수
  덱스터스튜디오:
    name: 덱스터스튜디오
    keywords:
    - DEXTER STUDIOS
    - DEXTER studios
    representative: 김욱
  엠라인스튜디오:
    name: 엠라인스튜디오
    keywords:
    - MLINE
    representative: 김윤필
  도도스튜디오:
    name: 도도스튜디오
    keywords:
    - 도도스튜디오
    representative: 김은진
  블라우비트:
    name: 블라우비트
    keywords:
    - 블라우비트
    representative: 김의선
  살린:
    name: 살린
    keywords:
    - 살린
    representative: 김재현
  SM엔터테인먼트:
    name: SM엔터테인먼트
    keywords:
    - SM ENTERTAINMENT GROUP
    representative: 김종민
  우신정보시스템:
    name: 우신정보시스템
    keywords:
    - 우신정보시스템
    representative: 김진영
  니에프스:
    name: 니에프스
    keywords:
    - 니에프스
    representative: 김창배
  대신증권:
    name: 대신증권
    keywords:
    - 대신증권
    representative: 김태욱
  갤럭시코퍼레이션:
    name: 갤럭시코퍼레이션
    keywords:
    - GALAXY CORP.
    representative: 김현정
  콕스스페이스:
    name: 콕스스페이스
    keywords:
    - COXSPACE
    representative: 김호연
  스토익엔터테인먼트:
    name: 스토익엔터테인먼트
    keywords:
    - 스토익엔터테인먼트
    representative: 김홍석
  한국열린사이버대학교:
    name: 한국열린사이버대학교
    keywords:
    - 한국열린사이버대학교
    representative: 남희양
  MBC:
    name: MBC
    keywords:
    - Munhwa Broadcasting Corp.
    representative: 노시용
  메타뷰:
    name: 메타뷰
    keywords:
    - 메타뷰
    representative: 노진송
  스코넥엔터테인먼트:
    name: 스코넥엔터테인먼트
    keywords:
    - 스코넥엔터테인먼트
    representative: 노충현
  스튜디오 엠버스703 (MBUS703):
    name: 스튜디오 엠버스703 (MBUS703)
    keywords:
    - 스튜디오 엠버스703 (MBUS703)
    representative: 노치욱 盧致煜 Chiwook Nho
  네오컨버전스:
    name: 네오컨버전스
    keywords:
    - 네오컨버전스
    representative: 류내원
  벤처스퀘어:
    name: 벤처스퀘어
    keywords:
    - VENTURE SQUARE
    representative: 명승은
  대진대학교:
    name: 대진대학교
    keywords:
    - 대진대학교
    representative: 문수지
  플레이파크:
    name: 플레이파크
    keywords:
    - 플레이파크
    representative: 박건웅
  (재)전남정보문화산업진흥원:
    name: (재)전남정보문화산업진흥원
    keywords:
    - (재)전남정보문화산업진흥원
    representative: 박근아
  와이엠엑스:
    name: 와이엠엑스
    keywords:
    - 와이엠엑스
    representative: 박근영
  세계미디어:
    name: 세계미디어
    keywords:
    - 세계미디어
    representative: 박동선
  두리번:
    name: 두리번
    keywords:
    - DOORIBUN
    representative: 박두환
  데이터킹:
    name: 데이터킹
    keywords:
    - DATAKING
    representative: 박선규
  다이브엑스알:
    name: 다이브엑스알
    keywords:
    - DIVEXR
    representative: 박선영
  KT이엔지코어:
    name: KT이엔지코어
    keywords:
    - kt engcore
    representative: 박성배
  에이치엔아이엑스:
    name: 에이치엔아이엑스
    keywords:
    - HNIX
    representative: 박성우
  페어엑스:
    name: 페어엑스
    keywords:
    - 페어엑스
    representative: 박세안
  루디벨:
    name: 루디벨
    keywords:
    - 루디벨
    representative: 박인혜
  유니티테크놀로지스코리아(유):
    name: 유니티테크놀로지스코리아(유)
    keywords:
    - 유니티테크놀로지스코리아(유)
    representative: 박중현
  리앤팍스:
    name: 리앤팍스
    keywords:
    - 리앤팍스
    representative: 박지호
  에이아이파크:
    name: 에이아이파크
    keywords:
    - 에이아이파크
    representative: 박철민
  이솔정보통신:
    name: 이솔정보통신
    keywords:
    - 이솔정보통신
    representative: 박평호
  아이피버스:
    name: 아이피버스
    keywords:
    - 아이피버스
    representative: 박희석
  비빔블:
    name: 비빔블
    keywords:
    - BIBIMBLE
    representative: 방준영
  에이치오 엔터테인먼트:
    name: 에이치오 엔터테인먼트
    keywords:
    - 에이치오 엔터테인먼트
    representative: 백성실
  HTC:
    name: HTC
    keywords:
    - HTC
    representative: 백승배
  빅토리아프로덕션:
    name: 빅토리아프로덕션
    keywords:
    - 빅토리아프로덕션
    representative: 빅토리아 한
  칸:
    name: 칸
    keywords:
    - 칸
    representative: 서국한
  삼성전자:
    name: 삼성전자
    keywords:
    - 삼성전자
    representative: 서영근
  드림브이알:
    name: 드림브이알
    keywords:
    - 드림브이알
    representative: 서영수
  베스트텍:
    name: 베스트텍
    keywords:
    - 베스트텍
    representative: 서우승
  유디포엠:
    name: 유디포엠
    keywords:
    - 유디포엠
    representative: 서정협
  에스아이오티인포텍:
    name: 에스아이오티인포텍
    keywords:
    - 에스아이오티인포텍
    representative: 서형준
  딥다이버스:
    name: 딥다이버스
    keywords:
    - 딥다이버스
    representative: 성기봉
  이노시뮬레이션:
    name: 이노시뮬레이션
    keywords:
    - 이노시뮬레이션
    representative: 성인제
  스튜디오쇼:
    name: 스튜디오쇼
    keywords:
    - STUDIO SHOH ENTERTAINMENT
    representative: 성지환
  슈퍼브이알:
    name: 슈퍼브이알
    keywords:
    - SUPER VR
    representative: 송민철
  홍익과학기술:
    name: 홍익과학기술
    keywords:
    - 홍익과학기술
    representative: 송영남
  삼우이머션:
    name: 삼우이머션
    keywords:
    - 삼우이머션
    representative: 송영진
  코드리치:
    name: 코드리치
    keywords:
    - CODEREACH
    representative: 송진우
  디티:
    name: 디티
    keywords:
    - DT
    representative: 신원호
  에이아이콘:
    name: 에이아이콘
    keywords:
    - AICON
    representative: 신준우
  한국항공우주산업:
    name: 한국항공우주산업
    keywords:
    - 한국항공우주산업
    representative: 안정일
  펄스나인:
    name: 펄스나인
    keywords:
    - Caretive / Pulse9
    representative: 양병석
  원유니버스:
    name: 원유니버스
    keywords:
    - 원유니버스
    representative: 양보근
  시공테크:
    name: 시공테크
    keywords:
    - 시공테크
    representative: 양성준
  에어에이알:
    name: 에어에이알
    keywords:
    - 에어에이알
    representative: 오성훈
  지캠:
    name: 지캠
    keywords:
    - Gcam
    representative: 오세광
  이퀄소울:
    name: 이퀄소울
    keywords:
    - EQUAL SOUL
    representative: 오제욱
  디오비스튜디오:
    name: 디오비스튜디오
    keywords:
    - 디오비스튜디오
    representative: 우성천
  한국과학기술원:
    name: 한국과학기술원
    keywords:
    - 한국과학기술원
    representative: 우운택
  크리에이터버스:
    name: 크리에이터버스
    keywords:
    - 크리에이터버스
    representative: 유승우
  맘모식스:
    name: 맘모식스
    keywords:
    - 맘모식스
    representative: 유철호
  엔피니티세븐:
    name: 엔피니티세븐
    keywords:
    - NFINITY 7
    representative: 윤승훈
  제이원스페이스:
    name: 제이원스페이스
    keywords:
    - 제이원스페이스
    representative: 윤영철
  쓰리디타다:
    name: 쓰리디타다
    keywords:
    - 쓰리디타다
    representative: 윤현모
  메타버스쇼:
    name: 메타버스쇼
    keywords:
    - 메타버스쇼
    representative: 이경용
  오버더핸드:
    name: 오버더핸드
    keywords:
    - OVER THE HAND
    representative: 이규승
  ST마이크로일렉트로닉스:
    name: ST마이크로일렉트로닉스
    keywords:
    - STMicroelectronics Asia Pacific Pte. Ltd
    representative: 이규진
  피앤씨솔루션:
    name: 피앤씨솔루션
    keywords:
    - 피앤씨솔루션
    representative: 이상윤
  플레이큐리오:
    name: 플레이큐리오
    keywords:
    - 플레이큐리오
    representative: 이상준
  메타로켓:
    name: 메타로켓
    keywords:
    - 메타로켓
    representative: 이상헌
  탕카:
    name: 탕카
    keywords:
    - TANGKA
    representative: 이석민
  JTBC:
    name: JTBC
    keywords:
    - Jtbc
    representative: 이선우
  스토리타코:
    name: 스토리타코
    keywords:
    - STORYTACO
    representative: 이승종
  국회미래연구원:
    name: 국회미래연구원
    keywords:
    - 국회미래연구원
    representative: 이승환
  콘텐츠클라우드:
    name: 콘텐츠클라우드
    keywords:
    - Contents Cloud
    representative: 이시윤
  프리다츠:
    name: 프리다츠
    keywords:
    - 프리다츠
    representative: 이용환
  글로벌 이코노믹:
    name: 글로벌 이코노믹
    keywords:
    - 글로벌 이코노믹
    representative: 이원용
  이노베이션시스템:
    name: 이노베이션시스템
    keywords:
    - 이노베이션시스템
    representative: 이유섭
  브이런치:
    name: 브이런치
    keywords:
    - VRUNCH
    representative: 이윤우
  휴멜로:
    name: 휴멜로
    keywords:
    - Humelo
    representative: 이자룡
  메타팩토리코퍼레이션:
    name: 메타팩토리코퍼레이션
    keywords:
    - 메타팩토리코퍼레이션
    representative: 이재일
  가우스랩:
    name: 가우스랩
    keywords:
    - GAUSS LAB
    representative: 이정근
  한국전자통신연구원:
    name: 한국전자통신연구원
    keywords:
    - 한국전자통신연구원
    representative: 이정익
  한국공학대학교:
    name: 한국공학대학교
    keywords:
    - 한국공학대학교
    representative: 이정준
  호텔롯데:
    name: 호텔롯데
    keywords:
    - 호텔롯데
    representative: 이정중
  친구친구티비:
    name: 친구친구티비
    keywords:
    - 친구친구티비
    representative: 이정환
  세종일렉트릭:
    name: 세종일렉트릭
    keywords:
    - 세종일렉트릭
    representative: 이종석
  버넥트:
    name: 버넥트
    keywords:
    - 버넥트
    representative: 이지욱
  시너스텍:
    name: 시너스텍
    keywords:
    - 시너스텍
    representative: 이진학
  브이리스브이알:
    name: 브이리스브이알
    keywords:
    - 브이리스브이알
    representative: 이창수
  딥인스펙션:
    name: 딥인스펙션
    keywords:
    - DEEP INSPECTION
    representative: 이철희
  전략과 실행:
    name: 전략과 실행
    keywords:
    - 전략과 실행
    representative: 이혁수
  클라이어스:
    name: 클라이어스
    keywords:
    - 클라이어스
    representative: 임문수
  에스원:
    name: 에스원
    keywords:
    - 에스원
    representative: 임승채
  미라클:
    name: 미라클
    keywords:
    - MIRACLE
    representative: 임용진
  콘텐츠코리아:
    name: 콘텐츠코리아
    keywords:
    - 콘텐츠코리아
    representative: 임충순
  이모션웨이브:
    name: 이모션웨이브
    keywords:
    - 이모션웨이브
    representative: 장순철
  새만금 메타버스체험관:
    name: 새만금 메타버스체험관
    keywords:
    - 새만금 메타버스체험관
    representative: 장호영
  다올자산운용:
    name: 다올자산운용
    keywords:
    - 다올자산운용
    representative: 전우석
  벤타엑스:
    name: 벤타엑스
    keywords:
    - VENTA X
    representative: 전우열
  애니펜:
    name: 애니펜
    keywords:
    - ANIPEN
    representative: 전재웅
  볼드스텝:
    name: 볼드스텝
    keywords:
    - 볼드스텝
    representative: 전진수
  비주얼라이트:
    name: 비주얼라이트
    keywords:
    - Visual Light
    representative: 정성근
  리타:
    name: 리타
    keywords:
    - LITA
    representative: 정승희
  특허법인 위더피플:
    name: 특허법인 위더피플
    keywords:
    - 특허법인 위더피플
    representative: 정연용
  제이앤컴퍼니:
    name: 제이앤컴퍼니
    keywords:
    - 제이앤컴퍼니
    representative: 정철화
  스페이스엘비스:
    name: 스페이스엘비스
    keywords:
    - SPACEELVIS
    representative: 조성호
  스카이터틀:
    name: 스카이터틀
    keywords:
    - 스카이터틀
    representative: 조정식
  한국메타버스산업협회:
    name: 한국메타버스산업협회
    keywords:
    - 한국메타버스산업협회
    representative: 주정현
  스튜디오리얼라이브 / STUDIOREALIVE:
    name: 스튜디오리얼라이브 / STUDIOREALIVE
    keywords:
    - 스튜디오리얼라이브 / STUDIOREALIVE
    representative: 지명구
  라이크코퍼레이션:
    name: 라이크코퍼레이션
    keywords:
    - 라이크코퍼레이션
    representative: 최강배
  스페이스에이디:
    name: 스페이스에이디
    keywords:
    - 스페이스에이디
    representative: 최돈출
  데이터마케팅코리아:
    name: 데이터마케팅코리아
    keywords:
    - 데이터마케팅코리아
    representative: 최석흠
  브이알크루:
    name: 브이알크루
    keywords:
    - 브이알크루
    representative: 최성광
  CJ제일제당:
    name: CJ제일제당
    keywords:
    - CJ제일제당
    representative: 최성원
  한국교육학술정보원:
    name: 한국교육학술정보원
    keywords:
    - 한국교육학술정보원
    representative: 최창우
  케이브이알 인터랙티브:
    name: 케이브이알 인터랙티브
    keywords:
    - 케이브이알 인터랙티브
    representative: 최태철
  퓨처디자이너스 | 라이프스퀘어:
    name: 퓨처디자이너스 | 라이프스퀘어
    keywords:
    - 퓨처디자이너스 | 라이프스퀘어
    representative: 최형욱 Hugh Choi
  이머시브캐스트:
    name: 이머시브캐스트
    keywords:
    - 이머시브캐스트
    representative: 한장희
  밀당:
    name: 밀당
    keywords:
    - 밀당
    representative: 허명건
  한국전자정보통신산업진흥회:
    name: 한국전자정보통신산업진흥회
    keywords:
    - 한국전자정보통신산업진흥회
    representative: 홍원기
  엑스알텍:
    name: 엑스알텍
    keywords:
    - 엑스알텍
    representative: 황창선
  (사)한국메타버스산업협회:
    name: (사)한국메타버스산업협회
    keywords:
    - (사)한국메타버스산업협회
    representative: 황철호
  패러블엔터테인먼트:
    name: 패러블엔터테인먼트
    keywords:
    - PARABLE Ent.
    representative: 함정훈
  어드밴스드RF:
    name: 어드밴스드RF
    keywords:
    - ADVANCED RF TECHNOLOGIES,
    representative: ANDREW JUN PhD
  직스테크놀로지:
    name: 직스테크놀로지
    keywords:
    - ZYX Technology .
    representative: Choi, Jongbok Andrew
  숭실대학교:
    name: 숭실대학교
    keywords:
    - Soongsil University
    representative: Jeong-A Park
  뷰덱스:
    name: 뷰덱스
    keywords:
    - VUDEX
    representative: Seok. Namkoong
  KBS:
    name: KBS
    keywords:
    - KBS
    representative: Seong-Jik KIM
  미스트플레이:
    name: 미스트플레이
    keywords:
    - 미스트플레이
    representative: Suzie Insuk Kim
  브이브이알: *id001
