members:
  ALCHERA:
    name: ALCHERA
    keywords:
    - ALCHERA
    representative: 강민수
  포니이엔티:
    name: 포니이엔티
    keywords:
    - 포니이엔티
    representative: 강민호
  KMA:
    name: KMA
    keywords:
    - KMA
    representative: 강석
  에스와이코마드:
    name: 에스와이코마드
    keywords:
    - 에스와이코마드
    representative: 강선영
  대교:
    name: 대교
    keywords:
    - 대교
    representative: 강순천
  시니스트:
    name: 시니스트
    keywords:
    - 시니스트
    representative: 강신래
  MIXCON ENTERTAINMENT:
    name: MIXCON ENTERTAINMENT
    keywords:
    - MIXCON ENTERTAINMENT
    representative: 강영수
  에쓰핀테크놀로지:
    name: 에쓰핀테크놀로지
    keywords:
    - 에쓰핀테크놀로지
    representative: 강지원
  VIVE STUDIOS:
    name: VIVE STUDIOS
    keywords:
    - VIVE STUDIOS
    representative: 고광민
  하남디지털캠프:
    name: 하남디지털캠프
    keywords:
    - 하남디지털캠프
    representative: 고명
  concreate:
    name: concreate
    keywords:
    - concreate
    representative: 고명미
  위치스:
    name: 위치스
    keywords:
    - 위치스
    representative: 고미아
  케타버스:
    name: 케타버스
    keywords:
    - 케타버스
    representative: 고욱
  비햅틱스:
    name: 비햅틱스
    keywords:
    - 비햅틱스
    representative: 곽기욱
  유니브이알:
    name: 유니브이알
    keywords:
    - 유니브이알
    representative: 곽태진
  포스트미디어:
    name: 포스트미디어
    keywords:
    - 포스트미디어
    representative: 국현규
  AMBERIN:
    name: AMBERIN
    keywords:
    - AMBERIN
    representative: 권기석
  ZENSTEM:
    name: ZENSTEM
    keywords:
    - ZENSTEM
    representative: 권순재
  LG유플러스:
    name: LG유플러스
    keywords:
    - LG유플러스
    representative: 권순홍
  헉미디어:
    name: 헉미디어
    keywords:
    - 헉미디어
    representative: 권오철
  아테크넷:
    name: 아테크넷
    keywords:
    - 아테크넷
    representative: 권정열
  스튜디오메타케이:
    name: 스튜디오메타케이
    keywords:
    - 스튜디오메타케이
    representative: 김광집
  서강대학교:
    name: 서강대학교
    keywords:
    - 서강대학교
    representative: 김군주
  READY MADE:
    name: READY MADE
    keywords:
    - READY MADE
    representative: 김기홍
  미래시티 글로벌:
    name: 미래시티 글로벌
    keywords:
    - 미래시티 글로벌
    representative: 김동우
  AIXLAB:
    name: AIXLAB
    keywords:
    - AIXLAB
    representative: 김민균
  이노 법률사무소:
    name: 이노 법률사무소
    keywords:
    - 이노 법률사무소
    representative: 김민기
  트러스테이:
    name: 트러스테이
    keywords:
    - 트러스테이
    representative: 김백선
  하나금융TI:
    name: 하나금융TI
    keywords:
    - 하나금융TI
    representative: 김병근
  LOCO:
    name: LOCO
    keywords:
    - LOCO
    representative: 김수련
  메타키움:
    name: 메타키움
    keywords:
    - 메타키움
    representative: 김영수
  DEXTER studios:
    name: DEXTER studios
    keywords:
    - DEXTER studios
    representative: 김욱
  MLINE:
    name: MLINE
    keywords:
    - MLINE
    representative: 김윤필
  도도스튜디오:
    name: 도도스튜디오
    keywords:
    - 도도스튜디오
    representative: 김은진
  블라우비트:
    name: 블라우비트
    keywords:
    - 블라우비트
    representative: 김의선
  살린:
    name: 살린
    keywords:
    - 살린
    representative: 김재현
  SM ENTERTAINMENT GROUP:
    name: SM ENTERTAINMENT GROUP
    keywords:
    - SM ENTERTAINMENT GROUP
    representative: 김종민
  우신정보시스템:
    name: 우신정보시스템
    keywords:
    - 우신정보시스템
    representative: 김진영
  니에프스:
    name: 니에프스
    keywords:
    - 니에프스
    representative: 김창배
  대신증권:
    name: 대신증권
    keywords:
    - 대신증권
    representative: 김태욱
  GALAXY CORP.:
    name: GALAXY CORP.
    keywords:
    - GALAXY CORP.
    representative: 김현정
  COXSPACE:
    name: COXSPACE
    keywords:
    - COXSPACE
    representative: 김호연
  스토익엔터테인먼트:
    name: 스토익엔터테인먼트
    keywords:
    - 스토익엔터테인먼트
    representative: 김홍석
  한국열린사이버대학교:
    name: 한국열린사이버대학교
    keywords:
    - 한국열린사이버대학교
    representative: 남희양
  Munhwa Broadcasting Corp.:
    name: Munhwa Broadcasting Corp.
    keywords:
    - Munhwa Broadcasting Corp.
    representative: 노시용
  메타뷰:
    name: 메타뷰
    keywords:
    - 메타뷰
    representative: 노진송
  스코넥엔터테인먼트:
    name: 스코넥엔터테인먼트
    keywords:
    - 스코넥엔터테인먼트
    representative: 노충현
  스튜디오 엠버스703 (MBUS703):
    name: 스튜디오 엠버스703 (MBUS703)
    keywords:
    - 스튜디오 엠버스703 (MBUS703)
    representative: 노치욱 盧致煜 Chiwook Nho
  네오컨버전스:
    name: 네오컨버전스
    keywords:
    - 네오컨버전스
    representative: 류내원
  VENTURE SQUARE:
    name: VENTURE SQUARE
    keywords:
    - VENTURE SQUARE
    representative: 명승은
  대진대학교:
    name: 대진대학교
    keywords:
    - 대진대학교
    representative: 문수지
  플레이파크:
    name: 플레이파크
    keywords:
    - 플레이파크
    representative: 박건웅
  (재)전남정보문화산업진흥원:
    name: (재)전남정보문화산업진흥원
    keywords:
    - (재)전남정보문화산업진흥원
    representative: 박근아
  와이엠엑스:
    name: 와이엠엑스
    keywords:
    - 와이엠엑스
    representative: 박근영
  세계미디어:
    name: 세계미디어
    keywords:
    - 세계미디어
    representative: 박동선
  DOORIBUN:
    name: DOORIBUN
    keywords:
    - DOORIBUN
    representative: 박두환
  LG 유플러스:
    name: LG 유플러스
    keywords:
    - LG 유플러스
    representative: 박명환
  DATAKING:
    name: DATAKING
    keywords:
    - DATAKING
    representative: 박선규
  DIVEXR:
    name: DIVEXR
    keywords:
    - DIVEXR
    representative: 박선영
  kt engcore:
    name: kt engcore
    keywords:
    - kt engcore
    representative: 박성배
  HNIX:
    name: HNIX
    keywords:
    - HNIX
    representative: 박성우
  페어엑스:
    name: 페어엑스
    keywords:
    - 페어엑스
    representative: 박세안
  루디벨:
    name: 루디벨
    keywords:
    - 루디벨
    representative: 박인혜
  유니티테크놀로지스코리아(유):
    name: 유니티테크놀로지스코리아(유)
    keywords:
    - 유니티테크놀로지스코리아(유)
    representative: 박중현
  리앤팍스:
    name: 리앤팍스
    keywords:
    - 리앤팍스
    representative: 박지호
  에이아이파크:
    name: 에이아이파크
    keywords:
    - 에이아이파크
    representative: 박철민
  이솔정보통신:
    name: 이솔정보통신
    keywords:
    - 이솔정보통신
    representative: 박평호
  아이피버스:
    name: 아이피버스
    keywords:
    - 아이피버스
    representative: 박희석
  BIBIMBLE:
    name: BIBIMBLE
    keywords:
    - BIBIMBLE
    representative: 방준영
  에이치오 엔터테인먼트:
    name: 에이치오 엔터테인먼트
    keywords:
    - 에이치오 엔터테인먼트
    representative: 백성실
  HTC:
    name: HTC
    keywords:
    - HTC
    representative: 백승배
  빅토리아프로덕션:
    name: 빅토리아프로덕션
    keywords:
    - 빅토리아프로덕션
    representative: 빅토리아 한
  칸:
    name: 칸
    keywords:
    - 칸
    representative: 서국한
  삼성전자:
    name: 삼성전자
    keywords:
    - 삼성전자
    representative: 서영근
  드림브이알:
    name: 드림브이알
    keywords:
    - 드림브이알
    representative: 서영수
  베스트텍:
    name: 베스트텍
    keywords:
    - 베스트텍
    representative: 서우승
  유디포엠:
    name: 유디포엠
    keywords:
    - 유디포엠
    representative: 서정협
  에스아이오티인포텍:
    name: 에스아이오티인포텍
    keywords:
    - 에스아이오티인포텍
    representative: 서형준
  딥다이버스:
    name: 딥다이버스
    keywords:
    - 딥다이버스
    representative: 성기봉
  이노시뮬레이션:
    name: 이노시뮬레이션
    keywords:
    - 이노시뮬레이션
    representative: 성인제
  STUDIO SHOH ENTERTAINMENT:
    name: STUDIO SHOH ENTERTAINMENT
    keywords:
    - STUDIO SHOH ENTERTAINMENT
    representative: 성지환
  SUPER VR:
    name: SUPER VR
    keywords:
    - SUPER VR
    representative: 송민철
  홍익과학기술:
    name: 홍익과학기술
    keywords:
    - 홍익과학기술
    representative: 송영남
  삼우이머션:
    name: 삼우이머션
    keywords:
    - 삼우이머션
    representative: 송영진
  CODEREACH:
    name: CODEREACH
    keywords:
    - CODEREACH
    representative: 송진우
  DT:
    name: DT
    keywords:
    - DT
    representative: 신원호
  AICON:
    name: AICON
    keywords:
    - AICON
    representative: 신준우
  한국항공우주산업:
    name: 한국항공우주산업
    keywords:
    - 한국항공우주산업
    representative: 안정일
  Caretive / Pulse9:
    name: Caretive / Pulse9
    keywords:
    - Caretive / Pulse9
    representative: 양병석
  원유니버스:
    name: 원유니버스
    keywords:
    - 원유니버스
    representative: 양보근
  시공테크:
    name: 시공테크
    keywords:
    - 시공테크
    representative: 양성준
  에어에이알:
    name: 에어에이알
    keywords:
    - 에어에이알
    representative: 오성훈
  Gcam:
    name: Gcam
    keywords:
    - Gcam
    representative: 오세광
  EQUAL SOUL:
    name: EQUAL SOUL
    keywords:
    - EQUAL SOUL
    representative: 오제욱
  디오비스튜디오:
    name: 디오비스튜디오
    keywords:
    - 디오비스튜디오
    representative: 우성천
  한국과학기술원:
    name: 한국과학기술원
    keywords:
    - 한국과학기술원
    representative: 우운택
  크리에이터버스:
    name: 크리에이터버스
    keywords:
    - 크리에이터버스
    representative: 유승우
  맘모식스:
    name: 맘모식스
    keywords:
    - 맘모식스
    representative: 유철호
  NFINITY 7:
    name: NFINITY 7
    keywords:
    - NFINITY 7
    representative: 윤승훈
  제이원스페이스:
    name: 제이원스페이스
    keywords:
    - 제이원스페이스
    representative: 윤영철
  쓰리디타다:
    name: 쓰리디타다
    keywords:
    - 쓰리디타다
    representative: 윤현모
  메타버스쇼:
    name: 메타버스쇼
    keywords:
    - 메타버스쇼
    representative: 이경용
  OVER THE HAND:
    name: OVER THE HAND
    keywords:
    - OVER THE HAND
    representative: 이규승
  STMicroelectronics Asia Pacific Pte. Ltd:
    name: STMicroelectronics Asia Pacific Pte. Ltd
    keywords:
    - STMicroelectronics Asia Pacific Pte. Ltd
    representative: 이규진
  피앤씨솔루션:
    name: 피앤씨솔루션
    keywords:
    - 피앤씨솔루션
    representative: 이상윤
  플레이큐리오:
    name: 플레이큐리오
    keywords:
    - 플레이큐리오
    representative: 이상준
  메타로켓:
    name: 메타로켓
    keywords:
    - 메타로켓
    representative: 이상헌
  TANGKA:
    name: TANGKA
    keywords:
    - TANGKA
    representative: 이석민
  Jtbc:
    name: Jtbc
    keywords:
    - Jtbc
    representative: 이선우
  STORYTACO:
    name: STORYTACO
    keywords:
    - STORYTACO
    representative: 이승종
  국회미래연구원:
    name: 국회미래연구원
    keywords:
    - 국회미래연구원
    representative: 이승환
  Contents Cloud:
    name: Contents Cloud
    keywords:
    - Contents Cloud
    representative: 이시윤
  프리다츠:
    name: 프리다츠
    keywords:
    - 프리다츠
    representative: 이용환
  글로벌 이코노믹:
    name: 글로벌 이코노믹
    keywords:
    - 글로벌 이코노믹
    representative: 이원용
  이노베이션시스템:
    name: 이노베이션시스템
    keywords:
    - 이노베이션시스템
    representative: 이유섭
  VRUNCH:
    name: VRUNCH
    keywords:
    - VRUNCH
    representative: 이윤우
  Humelo:
    name: Humelo
    keywords:
    - Humelo
    representative: 이자룡
  메타팩토리코퍼레이션:
    name: 메타팩토리코퍼레이션
    keywords:
    - 메타팩토리코퍼레이션
    representative: 이재일
  GAUSS LAB:
    name: GAUSS LAB
    keywords:
    - GAUSS LAB
    representative: 이정근
  한국전자통신연구원:
    name: 한국전자통신연구원
    keywords:
    - 한국전자통신연구원
    representative: 이정익
  한국공학대학교:
    name: 한국공학대학교
    keywords:
    - 한국공학대학교
    representative: 이정준
  호텔롯데:
    name: 호텔롯데
    keywords:
    - 호텔롯데
    representative: 이정중
  친구친구티비:
    name: 친구친구티비
    keywords:
    - 친구친구티비
    representative: 이정환
  세종일렉트릭:
    name: 세종일렉트릭
    keywords:
    - 세종일렉트릭
    representative: 이종석
  DEXTER STUDIOS:
    name: DEXTER STUDIOS
    keywords:
    - DEXTER STUDIOS
    representative: 이주원
  버넥트:
    name: 버넥트
    keywords:
    - 버넥트
    representative: 이지욱
  시너스텍:
    name: 시너스텍
    keywords:
    - 시너스텍
    representative: 이진학
  브이리스브이알:
    name: 브이리스브이알
    keywords:
    - 브이리스브이알
    representative: 이창수
  DEEP INSPECTION:
    name: DEEP INSPECTION
    keywords:
    - DEEP INSPECTION
    representative: 이철희
  전략과 실행:
    name: 전략과 실행
    keywords:
    - 전략과 실행
    representative: 이혁수
  클라이어스:
    name: 클라이어스
    keywords:
    - 클라이어스
    representative: 임문수
  에스원:
    name: 에스원
    keywords:
    - 에스원
    representative: 임승채
  MIRACLE:
    name: MIRACLE
    keywords:
    - MIRACLE
    representative: 임용진
  콘텐츠코리아:
    name: 콘텐츠코리아
    keywords:
    - 콘텐츠코리아
    representative: 임충순
  이모션웨이브:
    name: 이모션웨이브
    keywords:
    - 이모션웨이브
    representative: 장순철
  새만금 메타버스체험관:
    name: 새만금 메타버스체험관
    keywords:
    - 새만금 메타버스체험관
    representative: 장호영
  다올자산운용:
    name: 다올자산운용
    keywords:
    - 다올자산운용
    representative: 전우석
  VENTA X:
    name: VENTA X
    keywords:
    - VENTA X
    representative: 전우열
  ANIPEN:
    name: ANIPEN
    keywords:
    - ANIPEN
    representative: 전재웅
  볼드스텝:
    name: 볼드스텝
    keywords:
    - 볼드스텝
    representative: 전진수
  Visual Light:
    name: Visual Light
    keywords:
    - Visual Light
    representative: 정성근
  LITA:
    name: LITA
    keywords:
    - LITA
    representative: 정승희
  특허법인 위더피플:
    name: 특허법인 위더피플
    keywords:
    - 특허법인 위더피플
    representative: 정연용
  제이앤컴퍼니:
    name: 제이앤컴퍼니
    keywords:
    - 제이앤컴퍼니
    representative: 정철화
  SPACEELVIS:
    name: SPACEELVIS
    keywords:
    - SPACEELVIS
    representative: 조성호
  스카이터틀:
    name: 스카이터틀
    keywords:
    - 스카이터틀
    representative: 조정식
  한국메타버스산업협회:
    name: 한국메타버스산업협회
    keywords:
    - 한국메타버스산업협회
    representative: 주정현
  스튜디오리얼라이브 / STUDIOREALIVE:
    name: 스튜디오리얼라이브 / STUDIOREALIVE
    keywords:
    - 스튜디오리얼라이브 / STUDIOREALIVE
    representative: 지명구
  라이크코퍼레이션:
    name: 라이크코퍼레이션
    keywords:
    - 라이크코퍼레이션
    representative: 최강배
  스페이스에이디:
    name: 스페이스에이디
    keywords:
    - 스페이스에이디
    representative: 최돈출
  데이터마케팅코리아:
    name: 데이터마케팅코리아
    keywords:
    - 데이터마케팅코리아
    representative: 최석흠
  브이알크루:
    name: 브이알크루
    keywords:
    - 브이알크루
    representative: 최성광
  CJ제일제당:
    name: CJ제일제당
    keywords:
    - CJ제일제당
    representative: 최성원
  한국교육학술정보원:
    name: 한국교육학술정보원
    keywords:
    - 한국교육학술정보원
    representative: 최창우
  케이브이알 인터랙티브:
    name: 케이브이알 인터랙티브
    keywords:
    - 케이브이알 인터랙티브
    representative: 최태철
  퓨처디자이너스 | 라이프스퀘어:
    name: 퓨처디자이너스 | 라이프스퀘어
    keywords:
    - 퓨처디자이너스 | 라이프스퀘어
    representative: 최형욱 Hugh Choi
  이머시브캐스트:
    name: 이머시브캐스트
    keywords:
    - 이머시브캐스트
    representative: 한장희
  밀당:
    name: 밀당
    keywords:
    - 밀당
    representative: 허명건
  한국전자정보통신산업진흥회:
    name: 한국전자정보통신산업진흥회
    keywords:
    - 한국전자정보통신산업진흥회
    representative: 홍원기
  엑스알텍:
    name: 엑스알텍
    keywords:
    - 엑스알텍
    representative: 황창선
  (사)한국메타버스산업협회:
    name: (사)한국메타버스산업협회
    keywords:
    - (사)한국메타버스산업협회
    representative: 황철호
  PARABLE Ent.:
    name: PARABLE Ent.
    keywords:
    - PARABLE Ent.
    representative: 함정훈
  ADVANCED RF TECHNOLOGIES,:
    name: ADVANCED RF TECHNOLOGIES,
    keywords:
    - ADVANCED RF TECHNOLOGIES,
    representative: ANDREW JUN PhD
  ZYX Technology .:
    name: ZYX Technology .
    keywords:
    - ZYX Technology .
    representative: Choi, Jongbok Andrew
  Soongsil University:
    name: Soongsil University
    keywords:
    - Soongsil University
    representative: Jeong-A Park
  VUDEX:
    name: VUDEX
    keywords:
    - VUDEX
    representative: Seok. Namkoong
  KBS:
    name: KBS
    keywords:
    - KBS
    representative: Seong-Jik KIM
  미스트플레이:
    name: 미스트플레이
    keywords:
    - 미스트플레이
    representative: Suzie Insuk Kim
  VVR .:
    name: VVR .
    keywords:
    - VVR .
    representative: YoungHoon Mok
